"""Initial migration

Revision ID: 02e47c378f13
Revises: 
Create Date: 2026-01-26 17:25:11.325492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02e47c378f13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'INTERVIEW', 'ASSESSMENT', 'OFFER', 'REJECTED', 'UNKNOWN', name='applicationstatus'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('email_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_body_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_index(op.f('ix_jobapplication_company_name'), 'jobapplication', ['company_name'], unique=False)
    op.create_table('processinglog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('emails_processed', sa.Integer(), nullable=False),
    sa.Column('emails_new', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processinglog')
    op.drop_index(op.f('ix_jobapplication_company_name'), table_name='jobapplication')
    op.drop_table('jobapplication')
    # ### end Alembic commands ###
