"""Sync models with database

Revision ID: 4bd68282763f
Revises: 49ad2d9860ea
Create Date: 2026-02-02 20:49:24.449042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bd68282763f'
down_revision: Union[str, Sequence[str], None] = '49ad2d9860ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicationevent', 'old_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('APPLIED', 'INTERVIEW', 'ASSESSMENT', 'PENDING', 'COMMUNICATION', 'OFFER', 'REJECTED', 'UNKNOWN', name='applicationstatus'),
               existing_nullable=True,
               postgresql_using='old_status::applicationstatus')
    op.alter_column('applicationevent', 'new_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('APPLIED', 'INTERVIEW', 'ASSESSMENT', 'PENDING', 'COMMUNICATION', 'OFFER', 'REJECTED', 'UNKNOWN', name='applicationstatus'),
               existing_nullable=False,
               postgresql_using='new_status::applicationstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicationevent', 'new_status',
               existing_type=sa.Enum('APPLIED', 'INTERVIEW', 'ASSESSMENT', 'PENDING', 'COMMUNICATION', 'OFFER', 'REJECTED', 'UNKNOWN', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('applicationevent', 'old_status',
               existing_type=sa.Enum('APPLIED', 'INTERVIEW', 'ASSESSMENT', 'PENDING', 'COMMUNICATION', 'OFFER', 'REJECTED', 'UNKNOWN', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
