"""Add sender and closing details to JobApplication

Revision ID: 620102bf9550
Revises: 4ad32d28cac1
Create Date: 2026-01-27 14:13:55.196922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '620102bf9550'
down_revision: Union[str, Sequence[str], None] = '4ad32d28cac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobapplication', sa.Column('sender_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobapplication', sa.Column('email_closing', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobapplication', 'email_closing')
    op.drop_column('jobapplication', 'sender_email')
    op.drop_column('jobapplication', 'sender_name')
    # ### end Alembic commands ###
