"""Sync JobApplication model

Revision ID: 8041dd8a065b
Revises: 98bdae101f73
Create Date: 2026-01-27 12:23:47.944626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8041dd8a065b'
down_revision: Union[str, Sequence[str], None] = '98bdae101f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('applied_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('jobapplication_email_id_key'), 'jobapplication', type_='unique')
    op.drop_index(op.f('ix_jobapplication_company_name'), table_name='jobapplication')
    op.create_index(op.f('ix_jobapplication_company_name'), 'jobapplication', ['company_name'], unique=True)
    op.drop_column('jobapplication', 'email_date')
    op.drop_column('jobapplication', 'raw_body_hash')
    op.drop_column('jobapplication', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('email_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobapplication', sa.Column('raw_body_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobapplication', sa.Column('email_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_jobapplication_company_name'), table_name='jobapplication')
    op.create_index(op.f('ix_jobapplication_company_name'), 'jobapplication', ['company_name'], unique=False)
    op.create_unique_constraint(op.f('jobapplication_email_id_key'), 'jobapplication', ['email_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('jobapplication', 'applied_at')
    # ### end Alembic commands ###
