"""Add email_date column

Revision ID: 98bdae101f73
Revises: 02e47c378f13
Create Date: 2026-01-26 21:51:00.765004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98bdae101f73'
down_revision: Union[str, Sequence[str], None] = '02e47c378f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('email_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobapplication', 'email_date')
    # ### end Alembic commands ###
