"""Rename email_closing to summary

Revision ID: cdeec9e51d36
Revises: 620102bf9550
Create Date: 2026-01-27 14:34:34.082386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdeec9e51d36'
down_revision: Union[str, Sequence[str], None] = '620102bf9550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('jobapplication', 'email_closing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('email_closing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobapplication', 'summary')
    # ### end Alembic commands ###
